baseURL = 'https://xearthlayer.app/'
languageCode = 'en-us'
title = 'XEarthLayer'
theme = 'xearthlayer'

[params]
  description = "Stunning photoreal scenery for X-Plane 12. Download only what you need, when you need it."
  tagline = "Stunning photoreal scenery for X-Plane 12"
  author = "XEarthLayer Contributors"
  github = "https://github.com/samsoir/xearthlayer"
  discord = "https://discord.gg/XVUmMWYS"
  youtube = "https://www.youtube.com/channel/UCq8S6eiqK9OFIpcY0N66N1Q"
  kofi = "https://ko-fi.com/samsoir"

  # Latest release info (update on each release)
  latestVersion = "0.2.12"
  releaseDate = "2026-01-10"

  # Package library
  packageLibraryUrl = "/packages/xearthlayer_package_library.txt"

[menu]
  [[menu.main]]
    name = "Features"
    url = "/#features"
    weight = 1
  [[menu.main]]
    name = "Download"
    url = "/#download"
    weight = 2
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 3
  [[menu.main]]
    name = "Community"
    url = "/#community"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]
